name: cooperativeapp
description: HDS Cooperative App Project

version: 1.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
#  rest_client: ^1.0.6+2
  table_calendar: ^3.0.5
  flutter_calendar_carousel: ^2.1.0
  flutter:
    sdk: flutter
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.5
  double_back_to_close_app: ^2.0.1
  sizer: ^2.0.0
  dio: ^4.0.6
  #dio: ^5.3.2
  #http: ^0.13.5
  image_picker: ^0.8.5
  image: ^3.1.3
  meta: ^1.1.8
  path: ^1.6.4
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_serializable: ^6.2.0
  retrofit: ^3.0.1+1
  #google_fonts: ^2.3.3
  google_fonts: ^4.0.3
  #flutter_paystack: 1.0.5+1
  flutter_paystack: ^1.0.7
  adaptive_dialog: ^1.6.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  path_provider: ^2.0.10
  image_cropper: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.PNG"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
